# Generated by Django 4.0.6 on 2022-08-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productrecycled',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_recycled'),
        ),
        migrations.AlterField(
            model_name='productrecycled',
            name='price',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productrecycled',
            name='purchased_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productrecycled',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
