# Generated by Django 4.0.6 on 2022-08-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productrecycled_purchased_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrecycled',
            name='product',
        ),
        migrations.AddField(
            model_name='productrecycled',
            name='product',
            field=models.ManyToManyField(related_name='product_recycled', to='product.product'),
        ),
    ]
