# Generated by Django 4.0.6 on 2022-08-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0003_alter_pet_purchased_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fodder',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='staff_fodder', to='account.staff'),
            preserve_default=False,
        ),
    ]
