# Generated by Django 4.0.6 on 2022-08-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('main', '0004_fodder_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fodder',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fodder', to='account.staff'),
        ),
    ]
